"""add a column to the schema

Revision ID: 1f43c05a22a4
Revises: 20491b32f4de
Create Date: 2018-09-11 12:22:35.316752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f43c05a22a4'
down_revision = '20491b32f4de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'name')
    op.add_column('pitch', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'pitch', 'categories', ['category_id'], ['id'])
    op.drop_column('pitch', 'category')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitch', sa.Column('category', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'pitch', type_='foreignkey')
    op.drop_column('pitch', 'category_id')
    op.add_column('categories', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
