"""add to db schema

Revision ID: 20491b32f4de
Revises: 1f187e6edc42
Create Date: 2018-09-10 20:35:13.214385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20491b32f4de'
down_revision = '1f187e6edc42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('name', sa.String(length=255), nullable=True))
    op.drop_column('categories', 'name_')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('name_', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('categories', 'name')
    # ### end Alembic commands ###
